dev: declare includes explicitly and support publish subcommand for docs

diff --git a/Taskfile b/Taskfile
--- a/Taskfile
+++ b/Taskfile
@@ -1,4 +1,23 @@
 #!/usr/bin/env bash
 
-# TODO:refactor generate it from the main.bash
-source bin/lib/main.bash
+set -euo pipefail
+
+[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
+  echo "bash version 4 or higher is required" >&2
+  exit 1
+}
+
+include=(
+  bin/lib/core/*.bash
+  bin/lib/app/*.bash
+  bin/lib/docs/*.bash
+  bin/lib/tools/tools.bash # load it first cause PATH
+  bin/lib/tools/*.bash
+  bin/lib/utils/*.bash
+  bin/lib/main.bash
+)
+
+for script in "${include[@]}"; do
+  # shellcheck source=bin/lib/main.bash
+  source "${script}"
+done
